// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_login
 */
export type BodyLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ChangePassword
 *
 * Schema for password change.
 */
export type ChangePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginTempTokenResponse
 *
 * Response for POST /auth/login — step 1 of 2FA flow.
 */
export type LoginTempTokenResponse = {
    /**
     * Temp Token
     *
     * Short-lived token for TOTP verification
     */
    temp_token: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * PaginatedResponse[UserPublic]
 */
export type PaginatedResponseUserPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Skip
     */
    skip: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * RecoveryCodesGenerateResponse
 */
export type RecoveryCodesGenerateResponse = {
    /**
     * Codes
     *
     * Recovery codes (plaintext returned ONLY on generation)
     */
    codes: Array<string>;
    /**
     * Remaining Count
     *
     * Number of remaining unused codes
     */
    remaining_count: number;
    /**
     * Message
     */
    message?: string;
};

/**
 * RecoveryCodesStatusResponse
 */
export type RecoveryCodesStatusResponse = {
    /**
     * Remaining Count
     *
     * Number of remaining unused codes
     */
    remaining_count: number;
    /**
     * Message
     *
     * Status message
     */
    message: string;
};

/**
 * RecoveryVerifyRequest
 */
export type RecoveryVerifyRequest = {
    /**
     * Code
     *
     * Recovery code (format: XXXX-XXXX)
     */
    code: string;
    /**
     * Temp Token
     *
     * Temp token from login (for verification during login)
     */
    temp_token?: string | null;
};

/**
 * RecoveryVerifyResponse
 */
export type RecoveryVerifyResponse = {
    /**
     * Remaining Count
     *
     * Number of remaining unused codes
     */
    remaining_count: number;
    /**
     * Message
     *
     * Result message
     */
    message: string;
    /**
     * Access Token
     *
     * JWT access token (returned only on successful login via recovery code)
     */
    access_token?: string | null;
};

/**
 * TotpChallengeResponse
 *
 * Response for POST /auth/totp/challenge
 */
export type TotpChallengeResponse = {
    /**
     * Challenge Id
     *
     * Unique challenge ID for enrollment
     */
    challenge_id: string;
    /**
     * Expires In
     *
     * Seconds until challenge expires
     */
    expires_in: number;
};

/**
 * TotpEnrollResponse
 *
 * Response for POST /auth/totp/enroll
 */
export type TotpEnrollResponse = {
    /**
     * Secret
     *
     * Base32 encoded secret
     */
    secret: string;
    /**
     * Qr Code
     *
     * Base64 encoded PNG QR code
     */
    qr_code: string;
    /**
     * Otpauth Url
     *
     * OTPAuth URL for authenticator apps
     */
    otpauth_url: string;
};

/**
 * TotpStatusResponse
 *
 * Response for GET /auth/totp/status
 */
export type TotpStatusResponse = {
    /**
     * Is Enabled
     */
    is_enabled: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * TotpVerifyFlowAResponse
 *
 * Response for successful TOTP verification (Flow A — login)
 */
export type TotpVerifyFlowAResponse = {
    /**
     * Access Token
     *
     * JWT access token
     */
    access_token: string;
    /**
     * Token Type
     *
     * Token type
     */
    token_type?: string;
    /**
     * Expires In
     *
     * Token expiration in seconds
     */
    expires_in: number;
    /**
     * User
     *
     * User information
     */
    user: {
        [key: string]: unknown;
    };
};

/**
 * TotpVerifyFlowBResponse
 *
 * Response for successful TOTP enrollment (Flow B — enroll confirm)
 */
export type TotpVerifyFlowBResponse = {
    /**
     * Message
     *
     * Success message
     */
    message?: string;
    /**
     * Is Enabled
     *
     * TOTP enabled status
     */
    is_enabled?: boolean;
    /**
     * Recovery Codes
     *
     * Plaintext recovery codes generated after enrollment. Shown ONCE — user must save them.
     */
    recovery_codes?: Array<string>;
};

/**
 * TotpVerifyRequest
 *
 * Combined request for POST /auth/totp/verify.
 * Flow A (login):    provide temp_token + totp_code
 * Flow B (enroll):   provide challenge_id + totp_code
 */
export type TotpVerifyRequest = {
    /**
     * Temp Token
     *
     * Flow A: temp token from login
     */
    temp_token?: string | null;
    /**
     * Challenge Id
     *
     * Flow B: challenge ID from /auth/totp/challenge
     */
    challenge_id?: string | null;
    /**
     * Totp Code
     *
     * TOTP code from authenticator
     */
    totp_code: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Password
     */
    password: string;
};

/**
 * UserCreateResponse
 */
export type UserCreateResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserResetPasswordToken
 *
 * Schema for password reset token validation.
 */
export type UserResetPasswordToken = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: LoginTempTokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RegisterData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterErrors = {
    /**
     * Email already registered
     */
    409: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/auth/password-recovery/{email}';
};

export type RecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordError = RecoverPasswordErrors[keyof RecoverPasswordErrors];

export type RecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RecoverPasswordResponse = RecoverPasswordResponses[keyof RecoverPasswordResponses];

export type ResetPasswordData = {
    body: UserResetPasswordToken;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password/';
};

export type ResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type TotpStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/status';
};

export type TotpStatusResponses = {
    /**
     * Successful Response
     */
    200: TotpStatusResponse;
};

export type TotpStatusResponse2 = TotpStatusResponses[keyof TotpStatusResponses];

export type TotpEnrollData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/enroll';
};

export type TotpEnrollResponses = {
    /**
     * Successful Response
     */
    200: TotpEnrollResponse;
};

export type TotpEnrollResponse2 = TotpEnrollResponses[keyof TotpEnrollResponses];

export type TotpChallengeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/challenge';
};

export type TotpChallengeResponses = {
    /**
     * Successful Response
     */
    200: TotpChallengeResponse;
};

export type TotpChallengeResponse2 = TotpChallengeResponses[keyof TotpChallengeResponses];

export type TotpVerifyData = {
    body: TotpVerifyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/verify';
};

export type TotpVerifyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TotpVerifyError = TotpVerifyErrors[keyof TotpVerifyErrors];

export type TotpVerifyResponses = {
    /**
     * Response Totpverify
     *
     * Successful Response
     */
    200: TotpVerifyFlowAResponse | TotpVerifyFlowBResponse;
};

export type TotpVerifyResponse = TotpVerifyResponses[keyof TotpVerifyResponses];

export type GetRecoveryCodesStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/recovery';
};

export type GetRecoveryCodesStatusResponses = {
    /**
     * Successful Response
     */
    200: RecoveryCodesStatusResponse;
};

export type GetRecoveryCodesStatusResponse = GetRecoveryCodesStatusResponses[keyof GetRecoveryCodesStatusResponses];

export type GenerateRecoveryCodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/recovery';
};

export type GenerateRecoveryCodesResponses = {
    /**
     * Successful Response
     */
    200: RecoveryCodesGenerateResponse;
};

export type GenerateRecoveryCodesResponse = GenerateRecoveryCodesResponses[keyof GenerateRecoveryCodesResponses];

export type VerifyRecoveryCodeData = {
    body: RecoveryVerifyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/recovery/verify';
};

export type VerifyRecoveryCodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyRecoveryCodeError = VerifyRecoveryCodeErrors[keyof VerifyRecoveryCodeErrors];

export type VerifyRecoveryCodeResponses = {
    /**
     * Successful Response
     */
    200: RecoveryVerifyResponse;
};

export type VerifyRecoveryCodeResponse = VerifyRecoveryCodeResponses[keyof VerifyRecoveryCodeResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type ListUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseUserPublic;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserErrors = {
    /**
     * Email already registered
     */
    409: Message;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserCreateResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ChangePasswordData = {
    body: ChangePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];
